### ISSUE TITLE
createSchedule and inviteForm routes are unprotected

### ISSUE THREAD

**Issue by acaruso7** [acaruso7/Scheduler-App#28]
- /createSchedule is accessable without authentication

- /inviteForm crashes when accessed without authentication

- both of these routes should render an HTML pages informing the user that he or she must log in first

**Comment by TyrangYang** [comment]
I fix when you leave that, but right now it just protected by authentication. I think /createSchedule is fine since the authenticated user can create a new schedule whenever he want. However, the /inviteForm may be need some other authentication.
